#!/usr/bin/env python3
"""Extract current YouTube Live m3u8 streams and write youtube-live.m3u"""

import subprocess
import time
from datetime import datetime, timezone

CHANNELS = [
    ("France 24 English", "https://www.youtube.com/france24english/live"),
    ("Africanews", "https://www.youtube.com/africanews/live"),
    ("Euronews", "https://www.youtube.com/euronews/live"),
    ("Sky News", "https://www.youtube.com/@SkyNews/live"),
    ("Al Jazeera English", "https://www.youtube.com/@aljazeeraenglish/live"),
    ("NASA Live", "https://www.youtube.com/@NASA/live"),
    ("NASASpaceflight", "https://www.youtube.com/@NASASpaceflight/live"),
    ("National Geographic", "https://www.youtube.com/@NatGeo/live"),
    ("Sen (Earth from ISS)", "https://www.youtube.com/@Sen/live"),
    ("ABC News Australia", "https://www.youtube.com/@abcnewsaustralia/live"),
    ("TVC News Nigeria", "https://www.youtube.com/tvcnewsnigeria/live"),
    ("Channels TV Nigeria", "https://www.youtube.com/channelstelevision/live"),
]

def get_m3u8(url: str) -> str | None:
    try:
        out = subprocess.check_output(
            ["yt-dlp", "-g", "-f", "bv*", "--no-warnings", url],
            stderr=subprocess.STDOUT,
            timeout=30,
            text=True,
        )
        for line in out.strip().splitlines():
            line = line.strip()
            if line.startswith("http"):
                return line
    except Exception as e:
        print(f"Failed {url}: {e}")
    return None

def main():
    lines = [
        "#EXTM3U",
        f"# Updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "# Auto-generated by GitHub Action + yt-dlp",
        "# Links expire after a few hours",
        "",
    ]

    success = 0
    for title, url in CHANNELS:
        print(f"Fetching: {title}")
        m3u8 = get_m3u8(url)
        if m3u8:
            tvg = title.replace(" ", "").replace("(", "").replace(")", "")
            lines.append(f'#EXTINF:-1 tvg-id="{tvg}" group-title="YouTube Live",{title}')
            lines.append(m3u8)
            lines.append("")
            success += 1
            print(f"  OK")
        else:
            print(f"  SKIP")
        time.sleep(1.2)

    with open("youtube-live.m3u", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nDone. {success}/{len(CHANNELS)} channels written.")

if __name__ == "__main__":
    main()
